cms/urls.py
from django.conf.urls import patterns, include
from django.contrib import admin
import os

admin.autodiscover()
working_path = os.path.dirname( os.path.realpath( __file__ ) )

from coltrane.feeds import CategoryFeed, LatestEntriesFeed

feeds = { 'entries': LatestEntriesFeed,
        'categories': CategoryFeed }


urlpatterns = patterns( '',
    ( r'^admin/', include( admin.site.urls ) ),

    ( r'^tiny_mce/(?P<path>.*)$', 'django.views.static.serve',
        { 'document_root': '' + working_path + '/js/tiny_mce/' } ),

    ( r'^search/$', 'cms.search.views.search' ),

    ( r'^comments/', include( 'django.contrib.comments.urls' ) ),

    ( r'^weblog/categories/', include( 'coltrane.urls.categories' ) ),
    ( r'^weblog/links/', include( 'coltrane.urls.links' ) ),
    ( r'^weblog/tags/', include( 'coltrane.urls.tags' ) ),
    ( r'^weblog/', include( 'coltrane.urls.entries' ) ),
    ( r'^comments/', include( 'django.contrib.comments.urls' ) ),
    ( r'^weblog/feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', { 'feed_dict': feeds } ),

    ( r'^codeshare/', include( 'cab.urls.home' ) ),
    ( r'^codeshare/snippets/', include( 'cab.urls.snippets' ) ),
    ( r'^codeshare/languages/', include( 'cab.urls.languages' ) ),
    ( r'^codeshare/popular/', include( 'cab.urls.popular' ) ),
    ( r'^codeshare/tags/', include( 'cab.urls.tags' ) ),
    ( r'^codeshare/bookmarks/', include( 'cab.urls.bookmarks' ) ),
    ( r'^codeshare/ratings/', include( 'cab.urls.ratings' ) ),

    ( r'^codeshare/css/(?P<path>.*)$', 'django.views.static.serve',
        { 'document_root': '' + working_path + '/cab/css/' } ),

    ( r'', include( 'django.contrib.flatpages.urls' ) ),
 )

cms/cab/models.py
from cms.cab import managers
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from tagging.fields import TagField
import datetime
import tagging
from django.contrib.markup.templatetags.markup import markdown
from pygments import highlight, lexers

class Language( models.Model ):
    name = models.CharField( max_length = 100 )
    slug = models.SlugField( unique = True )
    language_code = models.CharField( max_length = 50 )
    mime_type = models.CharField( max_length = 100 )
    objects = managers.LanguageManager()

    class Meta:
        ordering = ['name']

    def __unicode__( self ):
        return self.name

    @models.permalink
    def get_absolute_url( self ):
        return ( 'cab_language_detail', (), { 'slug': self.slug } )

    def get_lexer( self ):
        return lexers.get_lexer_by_name( self.language_code )

class Snippet( models.Model ):
    title = models.CharField( max_length = 255 )
    language = models.ForeignKey( Language )
    author = models.ForeignKey( User )
    description = models.TextField()
    description_html = models.TextField( editable = False )
    code = models.TextField()
    highlighted_code = models.TextField( editable = False )
    pub_date = models.DateTimeField( editable = False )
    updated_date = models.DateTimeField( editable = False )
    objects = managers.SnippetManager()
    tags = TagField()

    class Meta:
        ordering = ['-pub_date']

    def __unicode__( self ):
        return self.title

    def save( self, force_insert = False, force_update = False ):
        if not self.id:
            self.pub_date = datetime.datetime.now()
        self.updated_date = datetime.datetime.now()
        self.description_html = markdown( self.description )
        #problem with pygments and htmlformatter due to last version
        #self.highlighted_code = self.highlight()
        super( Snippet, self ).save( force_insert, force_update )

    @models.permalink
    def get_absolute_url( self ):
        return ( 'cab_snippet_detail', (), { 'object_id': self.id } )

    def highlight( self ):
        return highlight( self.code,
                         self.language.get_lexer(),
                         self.formatters.HtmlFormatter() )

# See http://blog.sveri.de/index.php?/categories/2-Django
tagging.register( Snippet, tag_descriptor_attr = 'etags' )


class Bookmark( models.Model ):
    snippet = models.ForeignKey( Snippet )
    user = models.ForeignKey( User, related_name = 'cab_bookmarks' )
    date = models.DateTimeField( editable = False )

    class Meta:
        ordering = ['-date']

    def __unicode__( self ):
        return "%s bookmarked by %s" % ( self.snippet, self.user )

    # See http://blog.haydon.id.au/2008/09/10-finishing-code-sharing-application.html
    def save( self, **kwargs ):
        if not self.id:
            self.date = datetime.datetime.now()
        super( Bookmark, self ).save( **kwargs )


class Rating( models.Model ):
    RATING_UP = 1
    RATING_DOWN = -1
    RATING_CHOICES = ( ( RATING_UP, 'useful' ),
                      ( RATING_DOWN, 'not useful' ) )
    snippet = models.ForeignKey( Snippet )
    user = models.ForeignKey( User, related_name = 'cab_rating' )
    rating = models.IntegerField( choices = RATING_CHOICES )
    date = models.DateTimeField()

    def __unicode__( self ):
        return "%s rating %s (%s)" % ( self.user, self.snippet, self.get_rating_display() )

    def save( self ):
        if not self.id:
            self.date = datetime.datetime.now()
        super( Rating, self ).save()

    def get_score( self ):
        return self.rating_set.aggregate( Sum( 'rating' ) )

cms/cab/forms.py
from django import forms
from django.contrib.auth.models import User

class SignupForm( forms.Form ):

    username = forms.CharField( max_length = 30 )
    email = forms.EmailField()
    password1 = forms.CharField( max_length = 30, widget = forms.PasswordInput( render_value = False ) )
    password2 = forms.CharField( max_length = 30, widget = forms.PasswordInput( render_value = False ) )

    def clean_username( self ):
        try:
            User.objects.get( username = self.cleaned_data['username'] )
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError( "This username is already in use. Please choose another." )

    def clean( self ):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError( "You must type the same password each time" )
        return self.cleaned_data

    def save( self ):
        new_user = User.objects.create_user( username = self.cleaned_data['username'], email = self.cleaned_data['email'], password = self.cleaned_data['password1'] )
        return new_user




# Not needed.

# from django import forms
# from cab.models import Snippet, Language
# 
# class AddSnippetForm(forms.Form):
#     def __init__(self, author, *args, **kwargs):
#         super(AddSnippetForm, self).__init__(*args, **kwargs)
#         self.author = author
# 
#     title = forms.CharField(max_length=255)
#     description = forms.CharField(widget=forms.Textarea())
#     code = forms.CharField(widget=forms.Textarea())
#     tags = forms.CharField(max_length=255)
#     language = forms.ModelChoiceField(queryset=Language.objects.all())
#     
#     def save(self):
#         return Snippet.objects.create(title=self.cleaned_data['title'],
#                           description=self.cleaned_data['description'],
#                           code=self.cleaned_data['code'],
#                           tags=self.cleaned_data['tags'],
#                           author=self.author,
#                           language=self.cleaned_data['language'])

cms/cab/views/forms.py
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from cms.cab.forms import SignupForm

def signup( request ):
    if request.method == 'POST':
        form = SignupForm( data = request.POST )
        if form.is_valid():
            new_user = form.save()
            return HttpResponseRedirect( "/accounts/login/" )
    else:
        form = SignupForm()
    return render_to_response( 'signup.html', { 'form': form } )

from django import forms
from cms.cab.models import Snippet, Language

class AddSnippetForm( forms.Form ):
    def __init__( self, author, *args, **kwargs ):
        super( AddSnippetForm, self ).__init__( *args, **kwargs )
        self.author = author

    title = forms.CharField( max_length = 255 )
    description = forms.CharField( widget = forms.Textarea() )
    code = forms.CharField( widget = forms.Textarea() )
    tags = forms.CharField( max_length = 255 )
    language = forms.ModelChoiceField( queryset = Language.objects.all() )

    def save( self ):
        return Snippet.objects.create( title = self.cleaned_data['title'],
                          description = self.cleaned_data['description'],
                          code = self.cleaned_data['code'],
                          tags = self.cleaned_data['tags'],
                          author = self.author,
                          language = self.cleaned_data['language'] )

cms/cab/views/bookmarks.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render_to_response
from django.contrib.auth.decorators import login_required
from cms.cab.models import Bookmark, Snippet
from django.views.generic.list_detail import object_list
from django.template import RequestContext

def add_bookmark(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    try:
        Bookmark.objects.get(user__pk=request.user.id, snippet__pk=snippet_id)
    except Bookmark.DoesNotExist:
        Bookmark.objects.create( user = request.user, snippet = snippet )
    return HttpResponseRedirect(snippet.get_absolute_url())
add_bookmark = login_required(add_bookmark)

def delete_bookmark(request, snippet_id):
    if request.method == 'POST':
        snippet = get_object_or_404(Snippet, pk=snippet_id)
        Bookmark.objects.filter(user__pk=request.user.id, snippet__pk=snippet.id).delete()
        return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        return render_to_response('cab/confirm_bookmark_delete.html', 
                                    { 'snippet': snippet },
                                    context_instance=RequestContext(request))
delete_bookmark = login_required(delete_bookmark)

def user_bookmarks(request):
    return object_list(request,
                        queryset=Bookmark.objects.filter(user__pk=request.user.id),
                        template_name='cab/user_bookmarks.html',
                        paginate_by=20)

cms/cab/views/home.py
from django.shortcuts import render_to_response

def home(request):
    return render_to_response('cab/home.html')

cms/cab/views/languages.py
from django.shortcuts import get_object_or_404
from django.views.generic.list_detail import object_list
from cms.cab.models import Language

def language_detail(request, slug):
    language = get_object_or_404(Language, slug=slug)
    return object_list(request,
                        queryset=language.snippet_set.all(),
                        paginate_by=20,
                        template_name='cab/language_detail.html',
                        extra_context={ 'language': language })

cms/cab/views/popular.py
from cms.cab.models import Language, Snippet
from django.views.generic.list_detail import object_list

def top_authors(request):
    return object_list(request, queryset=Snippet.objects.top_authors(),
                        template_name='cab/top_authors.html',
                        paginate_by=20)

def top_languages(request):
    return object_list(request, queryset=Language.objects.top_languages(),
                        template_name='cab/top_languages.html',
                        paginate_by=20)

def most_bookmarked(request):
    return object_list(request, queryset=Snippet.objects.most_bookmarked(),
                        template_name='cab/most_bookmarked.html',
                        paginate_by=20)

def top_rated(request):
    return object_list(request, queryset=Snippet.objects.top_rated(),
                        template_name='cab/top_rated.html',
                        paginate_by=20)

cms/cab/views/ratings.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from cms.cab.models import Rating, Snippet

def rate(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    if 'rating' not in request.GET or request.GET['rating'] not in ('1', '-1'):
        return HttpResponseRedirect(snippet.get_absolute_url())
    try:
        rating = Rating.objects.get(user__pk=request.user.id, snippet__pk=snippet.id)
    except Rating.DoesNotExist:
        rating = Rating(user=request.user, snippet=snippet)
    rating.rating = int(request.GET['rating'])
    rating.save()
    return HttpResponseRedirect(snippet.get_absolute_url())
rate = login_required(rate)

cms/cab/views/snippets.py
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.forms import ModelForm
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from cms.cab.models import Snippet
from django.shortcuts import get_object_or_404
from django.template import RequestContext

class SnippetForm(ModelForm):
    class Meta:
        model = Snippet
        exclude = ['author']
    
def add_snippet(request):
    if request.method == 'POST':
        form = SnippetForm(data=request.POST)
        if form.is_valid():
            new_snippet = form.save(commit=False)
            new_snippet.author = request.user
            new_snippet.save()
            return HttpResponseRedirect(new_snippet.get_absolute_url())
    else:
        form = SnippetForm()
    return render_to_response('cab/snippet_form.html', 
                                { 'form': form, 'add': True },
                                context_instance=RequestContext(request))
add_snippet = login_required(add_snippet)

def edit_snippet(request, snippet_id):
    snippet = get_object_or_404(Snippet, pk=snippet_id)
    if request.user.id != snippet.author.id:
        return HttpResponseForbidden()
    if request.method == 'POST':
        form = SnippetForm(instance=snippet, data=request.POST)
        if form.is_valid():
            snippet = form.save()
            return HttpResponseRedirect(snippet.get_absolute_url())
    else:
        form = SnippetForm(instance=snippet)
    return render_to_response('cab/snippet_form.html',
                                { 'form': form, 'add': False },
                                context_instance=RequestContext(request))
edit_snippet = login_required(edit_snippet)
        

cms/templates/cab/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Code Sharing {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/codeshare/css/pygments.css" type="text/css" />
</head>
<body>
    <div id="header">
        <h1 id="branding">Code sharing</h1>
        <p><a href="{% url cab_home %}">Home page</a></p>
    </div>
    
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    
</body>
</html>

cms/templates/cab/confirm_bookmark_delete.html
{% extends "cab/base.html" %}

{% block title %} | Delete Bookmark?{% endblock %}


{% block content %}
    <h2>Delete Bookmark?</h2>

    <ul>
    <li>Title: {{ snippet.title }}</li>
    <li>Published: {{ snippet.pub_date }}</li>
    <li>Updated: {{ snippet.updated_date }}</li>
    <li>Language: {{ snippet.language }}</li>
    <li>Author: {{ snippet.author }}</li>
    </ul>

    <form method="post" action="">
        <p><input type="submit" value="Delete bookmark"></p>
    </form>
    
{% endblock %}

cms/templates/cab/home.html
{% extends "cab/base.html" %}

{% block title %}{% endblock %}


{% block content %}
    <h2>Home</h2>

    <p>[An extra page I added to make it easier to get to everything.]</p>
    
    <ul>
    <li><a href="{% url cab_language_list %}">Languages</a></li>
    <li><a href="{% url cab_snippet_list %}">Snippets</a></li>
    <li><a href="{% url cab_top_authors %}">Top Authors</a></li>
    <li><a href="{% url cab_top_languages %}">Top Languages</a></li>
    <li><a href="{% url cab_most_bookmarked %}">Most Bookmarked</a></li>
    <li><a href="{% url cab_top_rated %}">Top Rated</a></li>
    <li><a href="{% url cab_user_bookmarks %}">User bookmarks</a></li>
    </ul>
    
{% endblock %}

cms/templates/cab/language_detail.html
{% extends "cab/base.html" %}

{% block title %} | Language | {{ language.name }}{% endblock %}


{% block content %}
    <h2>{{ language.name }}</h2>

    {% if object_list %}
        {% for snippet in object_list %}
          <p><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></p>
         {% endfor %}
    {% else %}
        <p>There are no Snippets to display.</p>
    {% endif %}

{% endblock %}

cms/templates/cab/language_list.html
{% extends "cab/base.html" %}

{% block title %} | Languages{% endblock %}


{% block content %}
    <h2>Languages</h2>
    
    {% if object_list %}
        <ul>
        {% for language in object_list %}
            <li><a href="{{ language.get_absolute_url }}">{{ language.name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Languages to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}

cms/templates/cab/most_bookmarked.html
{% extends "cab/base.html" %}

{% block title %} | Most Bookmarked{% endblock %}


{% block content %}
    <h2>Most Bookmarked</h2>

    {% if object_list %}
        <ol>
        {% for snippet in object_list %}
            <li><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></li>
        {% endfor %}
        </ol>
    {% else %}
        <p>There are no Snippets to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}

cms/templates/cab/signup.html
<html>
<head>
<title>Sign up for an account</title>
</head>
<body>
<h1>Sign up for an account</h1>
<p>Use the form below to register for your new account; all
fields are required.</p>
<form method="post" action="">
{% if form.non_field_errors %}
<p><span class="error">
{{ form.non_field_errors|join:", " }}
</span></p>
{% endif %}
<p>{% if form.username.errors %}
<span class="error">{{ form.username.errors|join:", " }}</span>
{% endif %}</p>
<p><label for="id_username">Username:</label>
{{ form.username }}</p>
<p>{% if form.email.errors %}
<span class="error">
{{ form.email.errors|join:", " }}
</span>
{% endif %}</p>
<p><label for="id_name">Your e-mail address:</label>
{{ form.email }}</p>
<p>{% if form.password1.errors %}
<span class="error">
{{ form.passsword1.errors|join:", " }}
</span>
{% endif %}</p>
<p><label for="id_password1">Password:</label>
{{ form.password1 }}</p>
<p>{% if form.password2.errors %}
<span class="error">
{{ form.passsword2.errors|join:", " }}
</span>
{% endif %}</p>
<p><label for="id_password2">Password (again, to catch
typos): </label>
{{ form.password2 }}</p>
<p><input type="submit" value="Submit"></p>
</form>
</body>
</html>

cms/templates/cab/snippet_detail.html
{% extends "cab/base.html" %}

{% block title %} | Snippet | {{ object.title }}{% endblock %}


{% block content %}
    <h2>{{ object.title }}</h2>

    <ul>
    <li>Published: {{ object.pub_date }}</li>
    <li>Updated: {{ object.updated_date }}</li>
    <li>Language:  <a href="{{ object.language.get_absolute_url }}">{{ object.language }}</a></li>
    <li>Author: {{ object.author }}</li>
    <li>Tags: 
        {% if object.etags.count %}
                {% for tag in object.etags %}
                    <a href="{% url cab_snippet_archive_tag tag.name %}">{{ tag.name }}</a>
                    {% if forloop.last %}{% else %}
                        {% ifequal forloop.revcounter0 1 %}and {% else %}, {% endifequal %}
                    {% endif %}
                {% endfor %}
        {% else %}
            This Snippet doesn't have any tags.
        {% endif %}
    </li>
    </ul>
    
    {% load snippets %}
    {% if_bookmarked user object %}
        <form method="post" action="{% url cab_bookmark_delete object.id %}">
            <p><input type="submit" value="Delete bookmark"></p>
        </form>
    {% else %}
        <p><a href="{% url cab_bookmark_add object.id %}">Add bookmark</a></p>
    {% endif_bookmarked %}
    
    {% if_rated user object %}
        {% get_rating user object as rating %}
        <p>You rated this snippet {{ rating.get_rating_display }}.</p>
    {% else %}
        <p>Rate this snippet:
            <a href="{% url cab_snippet_rate object.id %}?rating=1">useful</a> or 
            <a href="{% url cab_snippet_rate object.id %}?rating=-1">not useful</a>.</p>  
    {% endif_rated %}
    
    {% load markup %}
    
    <p>{{ object.description_html|markdown }}</p>
    
    <p>
    {{ object.highlighted_code|markdown }}
    </p>

{% endblock %}

cms/templates/cab/snippet_form.html
{% extends "cab/base.html" %}

{% block title %} | {% if add %}Add a{% else %}Edit your{% endif %} Snippet{% endblock %}


{% block content %}
    <h2>{% if add %}Add a{% else %}Edit your{% endif %} Snippet</h2>

    <p>Use the form below to {% if add %}add a{% else %}edit your{% endif %} snippet; all fields are required.</p>

    <form method="post" action="">
        {{ form.as_p }}
        <p><input type="submit" value="Submit"></p>
    </form>
{% endblock %}

cms/templates/cab/snippet_list.html
{% extends "cab/base.html" %}

{% block title %} | Snippets{% endblock %}


{% block content %}
    <h2>Snippets</h2>
    
    {% if object_list %}
        <ul>
        {% for snippet in object_list %}
            <li><a href="{{ snippet.get_absolute_url }}">{{ snippet.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no Snippets to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}

cms/templates/cab/snippets_by_tag.html
{% extends "cab/base.html" %}

{% block title %} | Snippets tagged with '{{ tag.name }}'{% endblock %}


{% block content %}
    <h2>Snippets tagged with '{{ tag.name }}'</h2>

    {% for object in object_list %}
      <p><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></p>
    {% endfor %}

{% endblock %}

cms/templates/cab/top_authors.html
{% extends "cab/base.html" %}

{% block title %} | Top Authors{% endblock %}


{% block content %}
    <h2>Top Authors</h2>

    {% if object_list %}
        <ol>
        {% for author in object_list %}
            <li>{{ author.username }}</li>
        {% endfor %}
        </ol>
    {% else %}
        <p>There are no Authors to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}

cms/templates/cab/top_languages.html
{% extends "cab/base.html" %}

{% block title %} | Top Languages{% endblock %}


{% block content %}
    <h2>Top Languages</h2>

    {% if object_list %}
        <ol>
        {% for language in object_list %}
            <li><a href="{{ language.get_absolute_url }}">{{ language.name }}</a></li>
        {% endfor %}
        </ol>
    {% else %}
        <p>There are no Authors to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}

cms/templates/cab/user_bookmarks.html
{% extends "cab/base.html" %}

{% block title %} | Your Bookmarks{% endblock %}


{% block content %}
    <h2>Your Bookmarks</h2>

    {% if object_list %}
        <ol>
        {% for bookmark in object_list %}
            <li><a href="{{ bookmark.snippet.get_absolute_url }}">{{ bookmark.snippet.title }}</a></li>
        {% endfor %}
        </ol>
    {% else %}
        <p>There are no Snippets to display.</p>
    {% endif %}
    
    <!-- Tweaks from http://www.protocolostomy.com/2009/08/09/django-pygments-templates-code-sharing-and-design/ -->
    <p>
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">Previous page</a>
    {% endif %}
    {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next page</a>
    {% endif %}
    </p>
    
{% endblock %}